apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base.yaml

components:
- ../../infra/sidecar

configMapGenerator:
- name: db-routing
  files:
  - db-routing.yaml
- name: envoy-lua-http-filter
  behavior: replace
  files:
  - http-filter.lua=envoy-filter.lua

patches:
# The Envoy sidecar is configured to forward HTTP requests to `localhost:8080`.
# So we've got to start Quantum Leap on port 8080.
- target:
    kind: Deployment
    name: quantumleap
  path: add-port-arg.yaml
# The base YAML comes with a Service `targetPort` of 8080. That's not what
# we want since the Service should forward to Envoy which is on port 8181.
- target:
    kind: Service
    name: quantumleap
  path: replace-svc-target-port.yaml
