apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base.yaml

configMapGenerator:
- name: db-routing
  files:
  - db-routing.yaml

patchesStrategicMerge:
# At the moment, for sidecar injection to work there needs to be a "volumes"
# element in the deployment. So we add a dummy one just in case the Deployment
# that comes out after applying the values to the Helm chart does *not* have
# a "volumes" element. (If it does, our dummy one will be merged in, keeping
# whatever volumes came out of Helm.)
- add-dummy-volume.yaml

patchesJson6902:
# The Envoy sidecar is configured to forward HTTP requests to `localhost:8080`.
# So we've got to start Quantum Leap on port 8080.
- target:
    kind: Deployment
    name: quantumleap
  path: add-port-arg.yaml
# The base YAML comes with a Service `targetPort` of 8080. That's not what
# we want since the Service should forward to Envoy which is on port 8181.
- target:
    kind: Service
    name: quantumleap
  path: replace-svc-target-port.yaml
