apiVersion: apps/v1
kind: Deployment
metadata:
  name: ".*"
spec:
  template:
    spec:
      containers:
      - name: envoy
        image: "envoyproxy/envoy:v1.19.3"
        imagePullPolicy: IfNotPresent
        env:
        - name: loglevel
          value: debug
        ports:
        - containerPort: 8181
          name: http
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
