apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: envoy-config
  files:
  - envoy.yaml=envoy-config.yaml
- name: envoy-lua-http-filter
  files:
  - http-filter.lua=noop-filter.lua

patches:
- path: add-container.yaml
  target:
    kind: Deployment
