apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- opa.yaml

secretGenerator:
- name: opa-policy
  files:
  - rego/main.rego
  - fiware.service.rego=rego/fiware/service.rego
